version: '2.1'
services:
  web:
    container_name: app
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - "./local-db::/app/local-db"
    ports:
      - "3000:3000"